/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"
#include "stdio.h"
int *
add_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;
printf("Got the client request\n");
	/*
	 * insert server code here
	 */

	return &result;
}
